// Payment form
export const PAYMENT_FORM_RESET = 'PAYMENT_FORM_RESET';
export const PAYMENT_FORM_SET_ERROR = 'PAYMENT_FORM_SET_ERROR';
export const PAYMENT_FORM_CHANGE_DATA = 'PAYMENT_FORM_CHANGE_DATA';
export const PAYMENT_FORM_DELETE_ERROR = 'PAYMENT_FORM_DELETE_ERROR';
export const PAYMENT_FORM_RESET_BILLING = 'PAYMENT_FORM_RESET_BILLING';
export const PAYMENT_FORM_SET_ERROR_OBJECT = 'PAYMENT_FORM_SET_ERROR_OBJECT';
export const PAYMENT_FORM_SET_LOADING_STATUS = 'PAYMENT_FORM_SET_LOADING_STATUS';
export const PAYMENT_FORM_SET_BILLING_ADDRESS_STATUS = 'PAYMENT_FORM_SET_BILLING_ADDRESS_STATUS';

// Product info
export const PRODUCT_INFO_RESET = 'PRODUCT_INFO_RESET';
export const PRODUCT_INFO_SET_DATA = 'PRODUCT_INFO_SET_DATA';
export const PRODUCT_INFO_SET_LOADING_STATUS = 'PRODUCT_INFO_SET_LOADING_STATUS';
