// Items
export const CATALOG_ITEMS_RESET = 'CATALOG_ITEMS_RESET';
export const CATALOG_ITEMS_SET_LIST = 'CATALOG_ITEMS_SET_LIST';
export const CATALOG_ITEMS_RESET_TEXT = 'CATALOG_ITEMS_RESET_TEXT';
export const CATALOG_ITEMS_UNCHECK_ALL = 'CATALOG_ITEMS_UNCHECK_ALL';
export const CATALOG_ITEMS_DELETE_ITEM = 'CATALOG_ITEMS_DELETE_ITEM';
export const CATALOG_ITEMS_CHANGE_COUNT = 'CATALOG_ITEMS_CHANGE_COUNT';
export const CATALOG_ITEMS_SET_ERROR_TEXT = 'CATALOG_ITEMS_SET_ERROR_TEXT';
export const CATALOG_ITEMS_DELETE_ITEM_CHILD = 'CATALOG_ITEMS_DELETE_ITEM_CHILD';
export const CATALOG_ITEMS_TOGGLE_CHILD_CHECK = 'CATALOG_ITEMS_TOGGLE_CHILD_CHECK';
export const CATALOG_ITEMS_SET_REQUEST_STATUS = 'CATALOG_ITEMS_SET_REQUEST_STATUS';
export const CATALOG_ITEMS_TOGGLE_CHECK_FIRST_CHILDS = 'CATALOG_ITEMS_TOGGLE_CHECK_FIRST_CHILDS';
export const CATALOG_ITEMS_SET_CHECKED_FIRST_BTN_STATUS = 'CATALOG_ITEMS_SET_CHECKED_FIRST_BTN_STATUS';
