// Items
export const CATALOG_ITEMS_RESET = 'CATALOG_ITEMS_RESET';
export const CATALOG_ITEMS_SET_LIST = 'CATALOG_ITEMS_SET_LIST';
export const CATALOG_ITEMS_CREATE_ITEM = 'CATALOG_ITEMS_CREATE_ITEM';
export const CATALOG_ITEMS_UNCHECK_ALL = 'CATALOG_ITEMS_UNCHECK_ALL';
export const CATALOG_ITEMS_DELETE_ITEM = 'CATALOG_ITEMS_DELETE_ITEM';
export const CATALOG_ITEMS_SET_OPEN_ID = 'CATALOG_ITEMS_SET_OPEN_ID';
export const CATALOG_ITEMS_CHECK_CHILDS = 'CATALOG_ITEMS_CHECK_CHILDS';
export const CATALOG_ITEMS_CREATE_CHILD = 'CATALOG_ITEMS_CREATE_CHILD';
export const CATALOG_ITEMS_CHANGE_COUNT = 'CATALOG_ITEMS_CHANGE_COUNT';
export const CATALOG_ITEMS_RESET_OPEN_ID = 'CATALOG_ITEMS_RESET_OPEN_ID';
export const CATALOG_ITEMS_SET_ERROR_TEXT = 'CATALOG_ITEMS_SET_ERROR_TEXT';
export const CATALOG_ITEMS_DELETE_ITEM_CHILD = 'CATALOG_ITEMS_DELETE_ITEM_CHILD';
export const CATALOG_ITEMS_TOGGLE_CHILD_CHECK = 'CATALOG_ITEMS_TOGGLE_CHILD_CHECK';
export const CATALOG_ITEMS_SET_REQUEST_STATUS = 'CATALOG_ITEMS_SET_REQUEST_STATUS';

